export const ACTION = {
	MOVEMENT: 'MOVEMENT',
	MOVEMENT_DIRECT: 'MOVEMENT_DIRECT',
	MOVEMENT_REVERSE: 'MOVEMENT_REVERSE',
	MOVEMENT_MC_NOTIFICATION: 'MOVEMENT_MC_NOTIFICATION',

	TELEPORT_PERSON: 'TELEPORT_PERSON',
};
