export const ACTION = {
	MOVEMENT: 'MOVEMENT',
	MOVEMENT_DIRECT: 'MOVEMENT_DIRECT',
	MOVEMENT_REVERSE: 'MOVEMENT_REVERSE',
	ADD_SCORE: 'ADD_SCORE',

	// Send current person position in {x, y}
	MOVEMENT_OF_PERSON: 'MOVEMENT_MC_NOTIFICATION',
	// Notify about the collision
	COLLISION_WITH_TELEPORT: 'TELEPORT_PERSON',
};
